env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-empty-interface':
    - 'error'
    - allowSingleExtends: true
  'import/order':
    - 'error'
    - alphabetize:
        order: 'asc'
        caseInsensitive: true
      newlines-between: always
  'import/no-unresolved': 'off'
settings:
  import/resolver:
    typescript: true
    node: true
