extends:
  - 'plugin:vue/vue3-essential'
  - 'eslint:recommended'
  - '@vue/eslint-config-typescript'
  - '@vue/eslint-config-prettier/skip-formatting'
parserOptions:
  ecmaVersion: latest
rules:
  '@typescript-eslint/no-unused-vars': 'off'
  'vue/multi-word-component-names': 'off'
  'import/default': 'off'
